Spelling - Scatty: "Meine" (DE)
AmProsius/gothic-1-community-patch pull request #133
Opened 2021-04-03 20:47 UTC by AmProsius

**Describe the bug**
In the German localization there's a typo for a log entry concerning the defeat versus Kirgo.

**Changelog**
Im Tagebucheintrag nach dem Kampf gegen Kirgo die Phrase "Meinem Niederlage gegen Kirgo [...]" korrigiert zu "Meine Niederlage gegen Kirgo [...]".

2021-04-03 20:48 UTC, AmProsius commented
The fix works (tested manually ingame), but the automatic test fails. Maybe you can have a look at it, @szapp?

2021-04-04 09:28 UTC, szapp commented
> The fix works (tested manually ingame), but the automatic test fails. Maybe you can have a look at it, @szapp?

What’s the fail message?

2021-04-04 12:32 UTC, AmProsius commented
> What’s the fail message?

`Log topic entry was not added by the dialog function`

2021-04-04 12:43 UTC, szapp commented on src/Ninja/G1CP/Content/Tests/test133.d
> +    G1CP_LogRemoveTopic(topic);
The log topic is removed here and is not created during the dialog info function (unlike in #93). What will be necessary is to create it anew (see the lines 65-68).

2021-04-05 12:55 UTC, szapp requested changes

2021-04-05 12:55 UTC, szapp commented on src/Ninja/G1CP/Content/patchInit.d
> +        G1CP_133_DE_LogEntryScatty();                   // #133
This is a gamesave fix. It needs to be initialized from `G1CP_GamesaveFixes_Apply` and reverted in `G1CP_GamesaveFixes_Revert` not here.

2021-04-05 13:01 UTC, szapp approved these changes
Seems to work fine. I didn't to elaborate testing (no saving and loading) as it should be the same as #93.

2021-04-05 13:01 UTC, merged